version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: PostgresContainer 
    environment:
      POSTGRES_DB: gatortrader
      POSTGRES_USER: sammy
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql  # Updated path to init.sql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sammy -d gatortrader"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GatorTraderBackend
    ports:
      - "5000:5000"  # Adjust if your Flask app uses a different port
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always


volumes:
  postgres_data:

